<table data-toggle="table" class="table">
<div class="col-sm">
    </div>
    <div class="table-responsive"> 
    <h1>ACTIVITIES.</h1>
    <table class="table table-striped table-light" style="color:gray;">

              <thead>
                <tr style="color:black;">
                  <th scope="col">No.</th>
                  <th scope="col">Event</th>
                  <th scope="col">Date</th>
                  <th scope="col"></th>
                  <th scope="col"></th>
                </tr>
              </thead>
    <tbody>
        <?php foreach($data as $item){?>
            <tr>
                <td><?php echo $item->name ?></td>
                <td><?php echo $item->date ?></td>
                <td><?php echo $item->detail ?></td>
                <td><a style="color:white;" href="<?php echo $this->url->getBaseUri(); ?>event/setId/<?php echo $act[$i]->id;?>" class="btn btn-info" id="edit<?php echo $act[$i]->actid;?>" name="edit<?php echo $act[$i]->actid;?>" value="<?php echo $act[$i]->actid;?>">edit</a></td>
                  <td><a href="<?php echo $this->url->getBaseUri(); ?>event/deleteId/<?php echo $act[$i]->id;?>" class="btn btn-danger">delete</a></td>
                </tr>
                </td>

        <?php } ?>
    </tbody>
</table>   

<center>
<a align="right" href="<?php echo $this->url->getBaseUri().'event/add' ?>" class="btn btn-info"> Add </a> 
<a href="<?php echo $this->url->getBaseUri() ?>" class="btn btn-warning"> Back </a>
