<div class="container">
        <section id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">About</h2>
            <h3 class="section-subheading text-muted">My Profile</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <ul class="timeline">
              <li>
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="img/about/1.jpg" alt="">
                </div>
                <div class="timeline-panel">
                  <div class="timeline-heading">
                    <h4>600610776</h4>
                    <h4 class="subheading">Saratchun Botaen</h4>
                  </div>
                  <div class="timeline-body">
                    <p class="text-muted">Hello my name is Saratchun Botaen 600610776 Engineering Chaingmai University</p>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
       
        
</div>