<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EventDB</title>
    <?php echo $this->assets->outputCss('styles'); ?>    
    <?php echo $this->assets->outputJs('scripts'); ?> 
  </head>
    <body id="page-top" >

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>">Home?</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>event">Event</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link js-scroll-trigger" href="about">about</a>
            </li>
          </ul>
           <ul class="navbar-nav  navbar-right">     
   	<?php if($this->session->has('memberAuthen')) {?> 
     
   
      <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>profile"><?php echo $this->session->get('memberEmail');?></a>
     </li>
     <li class="nav-item mx-0 mx-lg-1">
     		<a  class="btn btn-danger navbar-btn" href="<?php echo $this->url->getBaseUri(); ?>authen/signOut"> Logout </a> 
     </li>  
    <?php } else {?>
      <li class="nav-item mx-0 mx-lg-1">
       <a href="<?php echo $this->url->getBaseUri(); ?>authen" class="btn btn-outline-primary"> Login </a>
      </li>    
     <li class="nav-item mx-0 mx-lg-1">
       <a href="<?php echo $this->url->getBaseUri(); ?>authen/signUp" class="btn btn-outline-info"> Sign Up </a>
      </li>
      <?php }?>
    </ul>
        </div>
      </div>
    </nav>

    <!-- Header -->
   
    <header class="masthead bg-primary text-white">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <center>
       <div class="container"><?php echo $this->getContent(); ?></div> 
       <br>
    </center>
    <br>
    <br>
    <br>
    <br>     
    </header>
    <!-- Footer -->  
    
    <div class="copyright py-4 bg-primary text-center text-white">
      <div class="container">
        <small>Copyright &copy; My Website 2018</small>
      </div>
    </div>
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>

    <script src="js/agency.min.js"></script>

  </body>
  
</html>
